/* Creación de usuario si estás trabajando con BD Oracle XE */
ALTER SESSION SET "_Oracle_Script"=TRUE;

CREATE USER PRY2206_P8 
IDENTIFIED BY "PRY2206.practica_8"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION TO PRY2206_P8;

GRANT RESOURCE TO PRY2206_P8;

ALTER USER PRY2206_P8 DEFAULT ROLE RESOURCE;




/* Creación de usuario si está trabajando con BD Oracle Cloud */
CREATE USER PRY2206_P8
IDENTIFIED BY "PRY2206.practica_8"
DEFAULT TABLESPACE DATA
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON DATA;

GRANT CREATE SESSION TO PRY2206_P8;

GRANT RESOURCE TO PRY2206_P8;

ALTER USER PRY2206_P8 DEFAULT ROLE RESOURCE;